services:
  streamer:
    build:
      context: ./streamer
      dockerfile: Dockerfile
    container_name: streamer
    restart: unless-stopped
    environment:
      - PORT=3000
    networks:
      - web
    ports:
      - "3000:3000"

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "${CADDY_IP:-0.0.0.0}:80:80"
      - "${CADDY_IP:-0.0.0.0}:443:443"
    volumes:
      - caddy_data:/data
      - ${DATA_FOLDER}/caddy_config:/config
      - ${DATA_FOLDER}/caddy_config/Caddyfile:/etc/caddy/Caddyfile
    networks:
      - web


networks:
  web:
    external: true

volumes:
  caddy_data:
