services:
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_SERVER_URL=${MINIO_SERVER_URL}
      - MINIO_BROWSER_REDIRECT_URL=${MINIO_BROWSER_REDIRECT_URL}
    volumes:
      # - minio_data:/data
      - ../components/S3_structure:/data/decapod:rw
    networks:
      - web
    ports:
      - "9000:9000"
      - "9001:9001"

networks:
  web:
    external: true

volumes:
  minio_data:
