services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - web
    ports:
      - "5432:5432"

networks:
  web:
    external: true

volumes:
  postgres_data:
    external: true
    name: infrastructure_postgres_data
